services:
  - type: web
    name: risk-engine-coordinator
    env: docker
    dockerfilePath: ./RiskEngine.Coordinator/Dockerfile
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: risk-engine-db
          property: connectionString
      - key: Jwt__Key
        generateValue: true
      - key: WorkerUrls__0
        value: "http://risk-engine-worker-1:8080"
      - key: WorkerUrls__1
        value: "http://risk-engine-worker-2:8080"
      
  - type: web
    name: risk-engine-worker-1
    env: docker
    dockerfilePath: ./RiskEngine.Worker/Dockerfile
    plan: free

  - type: web
    name: risk-engine-worker-2
    env: docker
    dockerfilePath: ./RiskEngine.Worker/Dockerfile
    plan: free

databases:
  - name: risk-engine-db
    databaseName: riskengine
    plan: free
